### PR TITLE
added info modal (no content)

### PR DESCRIPTION
**Pull request by mmamel**
Added info button that will bring up modal

No content yet but instrucntions will be added as text + css

### CODE REVIEW

**Comment by nickywongdong** [comment]
lol sorry i keep adding stuff to main

**Comment by nickywongdong** [comment]
basically just moved frontend into src/plannr.client

**Comment by mmamel** [comment]
Ohk cool. How do i start up local dev now?

**Comment by mmamel** [comment]
also wahts vite lol

**Comment by nickywongdong** [comment]
> Ohk cool. How do i start up local dev now?

You can keep using npm start in the src/plannr.client directory (make sure to npm install first)
Or you can just open the .sln file in visual studio and press play (might need to install extra dependencies in visual studio installer though)

**Comment by nickywongdong** [comment]
> also wahts vite lol

Seems like vite.js is a replacement for react-scripts build. Iwas just following this guide and it used it automatically:
https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022&source=recommendations

**Comment by mmamel** [comment]
theres no more npm start script in plannr.client/package.lock

**Comment by nickywongdong** [comment]
> theres no more npm start script in plannr.client/package.lock

oh try npm run dev

**Comment by mmamel** [comment]
did you have to set up any certificates?
`failed to load config from C:\Users\macmm\workspace\plannr\src\plannr.client\vite.config.js
error when starting dev server:
Error: Could not create certificate.
    at file:///C:/Users/macmm/workspace/plannr/src/plannr.client/vite.config.js.timestamp-1701223758042-58ac3a4a6fff4.mjs:29:11
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadConfigFromBundledFile (file:///C:/Users/macmm/workspace/plannr/src/plannr.client/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:67463:21)
    at async loadConfigFromFile (file:///C:/Users/macmm/workspace/plannr/src/plannr.client/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:67320:28)
    at async resolveConfig (file:///C:/Users/macmm/workspace/plannr/src/plannr.client/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:66924:28)
    at async _createServer (file:///C:/Users/macmm/workspace/plannr/src/plannr.client/node_modules/vite/dist/node/chunks/dep-vyqc0_aB.js:59492:20)
    at async CAC.<anonymous> (file:///C:/Users/macmm/workspace/plannr/src/plannr.client/node_modules/vite/dist/node/cli.js:764:24)`

**Comment by nickywongdong** [comment]
> Error: Could not create certificate. at

weird, let me try on another computer

**Pull request merged**
